### PR TITLE
Fixes rhythm and coop guitar bot

### PR DESCRIPTION
**Pull request by zigguy**
As the title says the rhythm and coop guitar bot were broken here's a [video](https://www.youtube.com/watch?v=1NySxZCm0kE) by Inventor211 showcasing this bug.
Also github is weird and it says i edited the entire file but, you can enable hide whitespace and it fixes this.

### CODE REVIEW

**Comment by EliteAsian123** [comment]
Hi, thanks for the PR. Unfortunately, I will not be merging this until you fix the “entire file edited” problem, as it messes up the blame and creates issues with conflicts. My best guess as to why this happens is because you maybe using the wrong line endings (`CR LF` vs `LF`).

Let me know when you've fixed this and I'll merge right away. Thanks!

**Comment by NarrikSynthfox** [comment]
Looks like its fixed now, only showing 2 additions now.

**Comment by zigguy** [comment]
Weird, its still saying I deleted a bunch of lines in the commit though.

**Comment by NarrikSynthfox** [comment]
I think if you squash the commits itll fix entirely? its cause the first commit replaced the file entirely, and the 2nd fixed the issues that caused that, so changes shows only the 2 changes but the commits show full file change

**Comment by zigguy** [comment]
I am just gonna create another PR because I have no clue how to do that and it will just be easier for me to create a new pr.

**Pull request closed without merging**
