### PR TITLE
Add scoring mechanics and UI

### PR DESCRIPTION
**Pull request by muskit**
On merge, it's OK to decline PlayScene alterations in the case of conflicts. We can just add the ScoreDisplay prefab back later.

### CODE REVIEW

**Comment by EliteAsian123** [comment]
OHHHHHH. Will be merged post update.

**Comment by muskit** [comment]
At this point, we're now just missing:
- harmony scoring (essentially bonus points)
- solo scoring

**Comment by muskit** [comment]
Remaining:
- saving
- harmony scoring (essentially bonus points)

**Comment by muskit** [comment]
saving complete! harmony can likely be done another time

**Comment by muskit** [comment]
i'll just finish harmony rq :)

**Pull request merged**
